example:
  enabled: false
  image:
    repository: gcr.io/jenkinsxio/example
    tag: 0.0.0
  runInterval: 30s # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"