{{- if .Values.jxPodStatus.enabled }}
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: jx-pod-status
  namespace: kuberhealthy
spec:
  runInterval: {{ .Values.jxPodStatus.runInterval }}
  timeout: {{ .Values.jxPodStatus.timeout }}
  podSpec:
    securityContext:
      runAsUser: 999
      fsGroup: 999
    containers:
      - env:
          - name: SKIP_DURATION
            value: "10m"
          {{- if not .Values.jxPodStatus.cluster.enabled }}
          - name: TARGET_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- end }}
        image: {{ .Values.jxPodStatus.image.repository }}:{{ .Values.jxPodStatus.image.tag }}
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
    serviceAccountName: jx-pod-status-sa
---
{{- if .Values.jxPodStatus.cluster.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jx-pod-status-check-rb
  namespace: jx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jx-pod-status-service-role
subjects:
  - kind: ServiceAccount
    name: jx-pod-status-sa
    namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-status-role
  namespace: kuberhealthy
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
{{- end }}
{{- if not .Values.jxPodStatus.cluster.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-status-role
  namespace: kuberhealthy
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-status-rb
  namespace: kuberhealthy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-status-role
subjects:
  - kind: ServiceAccount
    name: pod-status-sa
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx-pod-status-sa
  namespace: jx

{{- end }}