apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: chuck
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/pullrequest.yaml@versionStream
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
        - image: rawlingsj80/chuck:0.0.2
          name: chuck-it
          resources:
            requests:
              cpu: 100m
              memory: 200Mi

