apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: jx-bot-token
    context: jx-bot-token
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  - name: jx-install
    context: jx-install
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  - name: jx-pod-status
    context: jx-pod-status
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  - name: jx-secrets
    context: jx-secrets
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  - name: jx-webhooks
    context: jx-webhooks
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  - name: jx-webhook-events
    context: jx-webhook-events
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  - name: chuck
    context:  chuck
    always_run: false
    optional: false
    skip_report: true
    source: "chuck.yaml"
  postsubmits:
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$
