apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr-bot-check
    context: "pr-bot-check"
    always_run: true
    optional: false
    trigger: "/test bot-check"
    rerun_command: "/retest"
    source: "bot-check-pullrequest.yaml"
  postsubmits:
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - main
    - master
